version: "3.8"

services:
  redis:
    image: redis:7.0-alpine
    command: "redis-server --save 60 1 --loglevel warning"
    volumes:
      - './redis-data:/data'
    networks:
      - internal
    ports:
      - "6379:6379"

  bot:
    build:
      context: .
    networks:
      - internal
      - external
    env_file:
      - ".env"
    depends_on:
      - redis

networks:
  internal:
    internal: true
  external:
